baseURL: "https://dotu.dev/"
title: "Dogukan Turan"
paginate: 5
theme:
  - PaperMod
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
# disableKinds: ["sitemap"]

minify:
    disableXML: true
    minifyOutput: true

menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 100
    - identifier: pgp
      name: PGP
      url: /pgp/
      weight: 30

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  title: DevOpsGuy
  description: "A personal blog where I write what I've learned in devops and IT world"
  keywords: [DevOps, Software, Developer, DevSecOps, Cloud, GCP, AWS]
  author: Dogukan Turan
  DateFormat: "2006 January 2"
  defaultTheme: dark
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
      disableHLJS: false # to disable highlight.js
      disableFingerprinting: true
      favicon: "/posts/me.jpeg"
      favicon16x16: "/posts/me.jpeg"
      favicon32x32: "/posts/me.jpeg"
      apple_touch_icon: "/posts/me.jpeg"
      safari_pinned_tab: "/posts/me.jpeg"

  label:
      text: "ls /home/dogukan"
      icon: ""
      iconHeight: 45

  homeInfoParams:
      Title: ":(){ :|:& };:"
      Content: "DevOps Engineer at Kartaca"

  profileMode:
      enabled: true
      title: Dogukan Turan
      subtitle: "DevOps Engineer at Kartaca"
      imageUrl: "/posts/me.jpeg"
      imageWidth: 200
      imageHeight: 200
      imageTitle: image
      buttons:
          - name: Blog
            url: posts
          - name: Archives
            url: archives
          - name: CV
            url: https://rxresu.me/dogukanturanx/dogukan-turan

  socialIcons:
      - name: github
        url: "https://github.com/dogukanturan"
      - name: linkedin
        url: "https://linkedin.com/in/dogukanturan"
      - name: medium
        url: "https://devopsguy.medium.com"
      - name: twitter
        url: "https://twitter.com/imdotu"
      - name: RSS
        url: "/index.xml"
      - name: PGP
        url: "/pgp"

  cover:
      hidden: false
      hiddenInList: true
      hiddenInSingle: false
      linkFullImages: false

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]
